### ISSUE TITLE
pip install fails on 2nd run on fresh ubuntu 18.04 system

### ISSUE THREAD

**Issue by dankegel** [nexB/scancode-toolkit#1464]
This is a followup to https://github.com/nexB/scancode-toolkit/issues/1463

The first install on a fresh system works, but the second fails with a nasty segfault.
To repeat, for instance:

```
$ lxc launch ubuntu:18.04 demo-ubu1804
$ lxc exec demo-ubu1804
# apt update
# apt install python-pip libicu-dev
# su ubuntu
$ pip install --user scancode-toolkit
$ .local/bin/scancode --json-pp - --license --package .    (works!)
$ pip uninstall scancode-toolkit
$ pip install --user scancode-toolkit
...
Segmentation fault (core dumped)
```

A not-very-satisfactory workaround is ```$ rm -rf ~/.local```, but we can't expect users to ditch their whole environment to work around this.

A slightly less violent workaround is ```pip uninstall -y $(pip list --local --format=columns | awk 'NR>2 {print $1}')```

Next step is to see if uninstalling the packages one at a time until install succeeds narrows it down to a particular problem.

**Comment by pombredanne** [comment]
@dankegel thank you ++ for this detailed report and sorry for that.  I reckon that I have never a `--user` installation so this needs to be tested alright

**Comment by dankegel** [comment]
This is not particularly a scancode problem, I think, but alas, scancode suffers from someone else's sins.
Running under gdb shows the backtrace is the same as the one in https://bugs.python.org/issue27542

That bug suggests another approach - try installing each of the dependencies by itself to see if one of them is sufficient to trigger the bug.

It's also possible this will just go away with python 3.x :-) since presumably a lot of bugs have been fixed over the decade(s).

**Comment by dankegel** [comment]
The tip was useful.  Using it, I narrowed down the problem to a single package:
```
$ rm -rf ~/.local
$ pip install --user simplejson==3.16.0
Collecting simplejson==3.16.0
Installing collected packages: simplejson
Successfully installed simplejson-3.16.0
$ pip install --user simplejson==3.16.0
Collecting simplejson==3.16.0
Installing collected packages: simplejson
Successfully installed simplejson-3.16.0
Segmentation fault (core dumped)
```
Filed https://github.com/simplejson/simplejson/issues/245 for this.  It seems to be a bug in pip, perhaps tickled by something strange simplejson is doing.

**Comment by Abhishek-Dev09** [comment]
@dankegel :on ubuntu,I tried first time on fresh system on py3.6, it working fine .But after (second time) that it says segmentation fault(core dumped).But after installing pipev.It works fine.Last line is omitted that "scancode-tookit installed sucessfully."
http://dpaste.com/1VFKS5W
See similar problem: https://askubuntu.com/questions/467901/segmentation-fault-core-dumped-in-nam-ubuntu-14-04

**Comment by pombredanne** [comment]
Excellent and sleek! :bowing_man: 
FWIW the only reason why we use simplejson is for its ability to dump generators as JSON arrays which is something the standard lib `json` does not. (and still does not with the latest in Py2 and 3) :|

One alternative is to implement a simple default arg wraping a generator in a list but this means generators are loaded all in memory entirely  which will be an issue on larger scans.

Another would be to implement a pure Python JSON encoder for generators along [these lines](https://stackoverflow.com/questions/12670395/json-encoding-very-long-iterators/45482776)

**Comment by dankegel** [comment]
I think I figured out the simplejson crash thing in January but failed to leave enough breadcrumbs for my later forgetful self :-)

Anyone who runs into this should simply install a newer pip (or pipenv, or whatever).   https://github.com/nexB/scancode-toolkit/issues/1463 is also caused by old pip.

To be kind to users on stable distros that use an old pip, it would be good to also make an effort to paper over those problems if it's easy.  1463's probably really easy to safely paper over, by adding an explicit dependency.  This segfault... well, the pure Python JSON encoder looks like rather few lines of code, and reducing the number of third-party dependencies might make scancode more bulletproof and easier to distribute.

**Comment by dankegel** [comment]
If you're affected by this and are using Ubuntu 16.04 or Ubuntu 18.04, you can work around the problem by adding the PPA https://launchpad.net/~dank/+archive/ubuntu/python-fixes and grabbing an updated pip from there.

**Comment by pombredanne** [comment]
The supported OS/Python versions have changed quite a bit and I think this is no longer relevant.
Install runs fine on a fresh Ubuntu 16, 18 and 20 and these are all part of the test suites now so I think this is fine now.
Closing at last!
