### ISSUE TITLE
[Setup] Commonly encountered Errors while Setting Up

### ISSUE THREAD

**Issue by AyanSinhaMahapatra** [nexB/scancode-toolkit#1837]
Welcome! While setting up Scancode-Toolkit for the first time, users can encounter errors, but if common mistakes are avoided, we can get past many of the common roadblocks that first-time contributors encounter!

See this [page](https://scancode-toolkit.readthedocs.io/en/latest/index.html) to get started.

You can:

- Add the issues you encountered and solved later, for other people.
- Add new Errors/Issues.
- If you are sure it's a bug, report [here](https://github.com/nexB/scancode-toolkit/issues/new)

It's better if you follow these guidelines before you comment on this thread:

-  Add Errors/Solutions with Descriptions, Error Messages and Explanations, so others are able to easily follow.
- Make sure the same (or similar) error isn't already mentioned.
- Help each other out, be supportive and polite.
- Try to search for the problem here before you discuss it in Gitter Chat.

Report back at the above issue once you succeed, to encourage others and share what worked for you! Use :+1: to upvote already added reports.

**Comment by AyanSinhaMahapatra** [comment]
@pombredanne there's this pinned issue in Publiclab https://github.com/publiclab/plots2/issues/3840 and I also noticed a lot of people asking about errors (often the same type of errors) they encountered while setting up scancode in Gitter Chat, and since this issue.

**Comment by pombredanne** [comment]
@AyanSinhaMahapatra Thanks! I pinned this issue as suggested

**Comment by cls4242** [comment]
Hopelessly messed up installation process. It doesn't like Python27, try 3 - doesn't like that version - says to please use "system" python path. Python 2.7 gives a unicode path error where there isn't unicode in the path. Removed 2.7 and 3.8. Install 3.6 (no longer supported). Get that installed - and then get a message saying it needs a Python27.dll. 

I give up - I've spent 8 hours just trying to install this program. People can't be expected to do this. I was evaluating this for my company but it is obviously not ready for "prime time".

**Comment by cls4242** [comment]
Also, the link in the sentence that says to look here for common installation problems - goes to a "Page Not Found". Meh.

**Comment by mjherzog** [comment]
@cls4242 Sorry to hear that you have had so much trouble installing ScanCode Toolkit. It is hard to figure out why without information about your computer, but I have fixed the Page Not Found. The correct link is https://scancode-toolkit.readthedocs.io/en/latest/index.html.

**Comment by pombredanne** [comment]
@cls4242 Do you mind to start a new ticket and add your details so we can better help you? In particular we would need to know which OS and how you are do your install.
There is also a chat channel to request immediate help https://gitter.im/aboutcode-org/discuss

**Comment by jonCeg21** [comment]
posted this ticket 7 days ago. Almost no reaction. The community around this tool is not that great. The documentation is subpar. Windows 10 is not supported anymore change the documentation. Had a lot of headaches trying to make it work on Windows 10 and after that WSL for Windows. Still does not work.
See this ticket for setup problem: Unsupported Python, OS, platform or architecture: Only Python 64 bits 3.6 and above are supported #2448

**Comment by pombredanne** [comment]
@jonCeg21 I am sorry that you feel this way, as we are all trying hard and your configuration is not a common one.

**Comment by jonCeg21** [comment]
@pombredanne No problem I actually think this is a great plugin (not yet tried it myself). But it seems to have a lot of potential. But the documentation just needs to be updated a bit because I wasted a lot of time following leads that got me nowhere. But thank you for all the effort you and the community are making tho!

**Comment by pombredanne** [comment]
@jonCeg21 Thanks! let's us help you then! can you add more details in https://github.com/nexB/scancode-toolkit/issues/2448 ?

**Comment by pombredanne** [comment]
@AyanSinhaMahapatra do we still want this as a pinned issue?
I am closing for now and we can reopen if need be.
